version: "3"

services:
  postgresql:
    image: postgres:latest
    network_mode: bridge
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresdocker ql/data